apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "draforge.fullname" . }}-server
  labels:
    {{- include "draforge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "draforge.fullname" . }}-controller
  labels:
    {{- include "draforge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "draforge.fullname" . }}-node-plugin
  labels:
    {{- include "draforge.labels" . | nindent 4 }}
