apiVersion: v1
kind: Service
metadata:
  name: {{ include "draforge.fullname" . }}-server
  labels:
    {{- include "draforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "draforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
