#!/usr/bin/env bash
set -euo pipefail

pattern='claude|anthropic|copilot|openai|chatgpt|gemini|jules|co-authored|generated by (claude|anthropic|copilot|openai|chatgpt|gemini|jules)'
scan_output="$(
  grep -RniE "$pattern" . \
    --include='*.go' \
    --include='*.md' \
    --include='*.ts' \
    --include='*.tsx' \
    --include='*.yaml' \
    --include='*.yml' \
    --include='*.tf' \
    --include='*.sh' \
    --include='Dockerfile*' \
    --include='*.json' \
    --exclude='check-zero-attribution.sh' \
    --exclude-dir='.git' \
    --exclude-dir='node_modules' \
    --exclude-dir='dist' \
    --exclude-dir='.terraform' \
    || true
)"

if [[ -n "$scan_output" ]]; then
  printf '%s\n' "$scan_output"
  printf '\nZero attribution scan failed. Remove tool/vendor attribution strings from committed source files.\n' >&2
  exit 1
fi
